
---
- name: Install and Configure Samba on CentOS 7
  hosts: myhosts
  become: yes
  tasks:
    - name: Install Samba
      yum:
        name: samba
        state: present

    - name: Start and Enable Samba
      systemd:
        name: smb
        enabled: yes
        state: started

